<a href="https://colab.research.google.com/github/swarubm/NPTL-DS/blob/main/ToyotaP8_Dealing_with_Missing_value_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [28]:
import pandas as pd

In [29]:
cars = pd.read_csv('/content/Toyota.csv',index_col=0,na_values=["??","????"])
cars_data = cars.copy()

identifying null values

In [30]:
cars_data.isnull().sum()

Price          0
Age          100
KM            15
FuelType     100
HP             6
MetColor     150
Automatic      0
CC             0
Doors          0
Weight         0
dtype: int64

we have to check in the same row the values are missing or in the different rows other

In [31]:
missing = cars_data[cars_data.isnull().any(axis=1)]

In [32]:
missing

,Price,Age,KM,FuelType,HP,MetColor,Automatic,CC,Doors,Weight
2,13950,24.0,41711.0,Diesel,90.0,NaN,0,2000,3,1165
6,16900,27.0,NaN,Diesel,NaN,NaN,0,2000,3,1245
7,18600,30.0,75889.0,NaN,90.0,1.0,0,2000,3,1245
9,12950,23.0,71138.0,Diesel,NaN,NaN,0,1900,3,1105
15,22000,28.0,18739.0,Petrol,NaN,0.0,0,1800,3,1185
...,...,...,...,...,...,...,...,...,...,...
1428,8450,72.0,NaN,Petrol,86.0,NaN,0,1300,3,1015
1431,7500,NaN,20544.0,Petrol,86.0,1.0,0,1300,3,1025
1432,10845,72.0,NaN,Petrol,86.0,0.0,0,1300,3,1015
1433,8500,NaN,17016.0,Petrol,86.0,0.0,0,1300,3,1015
1434,7250,70.0,NaN,NaN,86.0,1.0,0,1300,3,1015

fill missing values with mean in numerical and categorical with most count

In [33]:
cars_data.describe()

,Price,Age,KM,HP,MetColor,Automatic,CC,Weight
count,1436.000000,1336.000000,1421.000000,1430.000000,1286.000000,1436.000000,1436.000000,1436.00000
mean,10730.824513,55.672156,68647.239972,101.478322,0.674961,0.055710,1566.827994,1072.45961
std,3626.964585,18.589804,37333.023589,14.768255,0.468572,0.229441,187.182436,52.64112
min,4350.000000,1.000000,1.000000,69.000000,0.000000,0.000000,1300.000000,1000.00000
25%,8450.000000,43.000000,43210.000000,90.000000,0.000000,0.000000,1400.000000,1040.00000
50%,9900.000000,60.000000,63634.000000,110.000000,1.000000,0.000000,1600.000000,1070.00000
75%,11950.000000,70.000000,87000.000000,110.000000,1.000000,0.000000,1600.000000,1085.00000
max,32500.000000,80.000000,243000.000000,192.000000,1.000000,1.000000,2000.000000,1615.00000

In [34]:
cars_data['Age'].mean()

np.float64(55.67215568862275)

In [35]:
cars_data['Age'].fillna(cars_data['Age'].mean(),inplace=True)

/tmp/ipython-input-2841206794.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  cars_data['Age'].fillna(cars_data['Age'].mean(),inplace=True)

In [37]:
cars_data

,Price,Age,KM,FuelType,HP,MetColor,Automatic,CC,Doors,Weight
0,13500,23.000000,46986.0,Diesel,90.0,1.0,0,2000,three,1165
1,13750,23.000000,72937.0,Diesel,90.0,1.0,0,2000,3,1165
2,13950,24.000000,41711.0,Diesel,90.0,NaN,0,2000,3,1165
3,14950,26.000000,48000.0,Diesel,90.0,0.0,0,2000,3,1165
4,13750,30.000000,38500.0,Diesel,90.0,0.0,0,2000,3,1170
...,...,...,...,...,...,...,...,...,...,...
1431,7500,55.672156,20544.0,Petrol,86.0,1.0,0,1300,3,1025
1432,10845,72.000000,NaN,Petrol,86.0,0.0,0,1300,3,1015
1433,8500,55.672156,17016.0,Petrol,86.0,0.0,0,1300,3,1015
1434,7250,70.000000,NaN,NaN,86.0,1.0,0,1300,3,1015
1435,6950,76.000000,1.0,Petrol,110.0,0.0,0,1600,5,1114

In [36]:
cars_data['KM'].median()

63634.0

In [41]:
cars_data['KM'].fillna(cars_data['KM'].median(),inplace=True)

/tmp/ipython-input-3320633750.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  cars_data['KM'].fillna(cars_data['KM'].median(),inplace=True)

In [42]:
cars_data["HP"].mean()

np.float64(101.47832167832168)

In [43]:
cars_data["HP"].fillna(cars_data["HP"].mean(),inplace=True)

/tmp/ipython-input-1078532056.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  cars_data["HP"].fillna(cars_data["HP"].mean(),inplace=True)

In [44]:
cars_data.isnull().sum()

Price          0
Age            0
KM             0
FuelType     100
HP             0
MetColor     150
Automatic      0
CC             0
Doors          0
Weight         0
dtype: int64

In [47]:
cars_data['FuelType'].value_counts()

FuelType
Petrol    1177
Diesel     144
CNG         15
Name: count, dtype: int64

as this is a categorical value we are replaceing with most occured term so in our particular dataset is the more oftenly repeated term thats why we are going to replace missing values with petrol

In [48]:
cars_data['FuelType'].value_counts().index[0]

'Petrol'

In [49]:
cars_data['FuelType'].fillna(cars_data['FuelType'].value_counts().index[0],inplace=True)

/tmp/ipython-input-2405634439.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  cars_data['FuelType'].fillna(cars_data['FuelType'].value_counts().index[0],inplace=True)

In [50]:
cars_data['MetColor'].mode()

0    1.0
Name: MetColor, dtype: float64

In [51]:
cars_data['MetColor'].fillna(cars_data['MetColor'].mode()[0],inplace=True)

/tmp/ipython-input-677269612.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  cars_data['MetColor'].fillna(cars_data['MetColor'].mode()[0],inplace=True)

In [52]:
cars_data.isnull().sum()

Price        0
Age          0
KM           0
FuelType     0
HP           0
MetColor     0
Automatic    0
CC           0
Doors        0
Weight       0
dtype: int64